controllers_front:
    resource: ../../src/Controller/Front
    type: annotation
    name_prefix: front_

controllers_back:
    resource: ../../src/Controller/Back
    type: annotation
    name_prefix: back_

controllers:
    resource: ../../src/Controller
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
